# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20160831_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='autors',
            new_name='autores',
        ),
    ]
